"""
pystl
"""
from __future__ import annotations
import typing
__all__ = ['TreeDict', 'TreeDictKeyIterator', 'TreeDictReverseKeyIterator']
class TreeDict:
    @staticmethod
    def fromkeys(iterable: typing.Iterable, value: typing.Any = None) -> TreeDict:
        ...
    def __contains__(self, arg0: typing.Any) -> bool:
        ...
    def __delitem__(self, arg0: typing.Any) -> None:
        ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        ...
    @typing.overload
    def __init__(self, **kwargs) -> None:
        ...
    @typing.overload
    def __init__(self, mapping: dict, **kwargs) -> None:
        ...
    @typing.overload
    def __init__(self, iterable: typing.Iterable, **kwargs) -> None:
        ...
    def __iter__(self) -> TreeDictKeyIterator:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __reversed__(self) -> TreeDictReverseKeyIterator:
        ...
    def __setitem__(self, key: typing.Any, value: typing.Any) -> None:
        ...
    def __str__(self) -> str:
        ...
    def clear(self) -> None:
        ...
    def copy(self) -> TreeDict:
        ...
    def get(self, key: typing.Any, default: typing.Any = None) -> typing.Any:
        ...
    def has_key(self, key: typing.Any) -> bool:
        ...
    def items(self) -> list[tuple[typing.Any, typing.Any]]:
        ...
    def keys(self) -> list[typing.Any]:
        ...
    @typing.overload
    def pop(self, key: typing.Any) -> typing.Any:
        ...
    @typing.overload
    def pop(self, key: typing.Any, default: typing.Any) -> typing.Any:
        ...
    def popitem(self) -> tuple[typing.Any, typing.Any]:
        ...
    @typing.overload
    def update(self, **kwargs) -> None:
        ...
    @typing.overload
    def update(self, mapping: dict, **kwargs) -> None:
        ...
    @typing.overload
    def update(self, iterable: typing.Iterable, **kwargs) -> None:
        ...
    def values(self) -> list[typing.Any]:
        ...
class TreeDictKeyIterator:
    def __iter__(self) -> TreeDictKeyIterator:
        ...
    def __next__(self) -> typing.Any:
        ...
class TreeDictReverseKeyIterator:
    def __iter__(self) -> TreeDictReverseKeyIterator:
        ...
    def __next__(self) -> typing.Any:
        ...
